# Static values for the gitlab chart. Dynamic values are configured directly in
# the helm_release resource.

global:
  minio:
    enabled: false

gitlab:
  unicorn:
    omniauth:
      enabled: true
      allowSingleSignOn: ['saml']
      blockAutoCreatedUsers: false
      autoLinkSamlUser: true
      providers: []

gitlab-runner:
  install: false

postgresql:
  install: false
